import { NextRequest, NextResponse } from "next/server"
import { runCreatorAI }              from "@/lib/agents/creator-ai"
import { sendLarkMessage }           from "@/lib/lark"
import { isCronReq }                 from "@/lib/analytics-helpers"

export const maxDuration = 300

// Cron: thứ 2 hàng tuần 9h ICT (02:00 UTC)
// vercel.json schedule: "0 2 * * 1"
// Tạo báo cáo tuần qua Gấu Pro → gửi Lark group

function getWeekRange(): { start: string; end: string; label: string } {
  const now  = new Date(new Date().toLocaleString("en-US", { timeZone: "Asia/Ho_Chi_Minh" }))
  const monday = new Date(now)
  monday.setDate(now.getDate() - 7 - ((now.getDay() + 6) % 7)) // tuần trước thứ 2
  const sunday = new Date(monday)
  sunday.setDate(monday.getDate() + 6)
  const fmt = (d: Date) => `${d.getDate().toString().padStart(2,"0")}/${(d.getMonth()+1).toString().padStart(2,"0")}`
  const fmtSql = (d: Date) => d.toISOString().slice(0, 10)
  return {
    start: fmtSql(monday),
    end:   fmtSql(sunday),
    label: `${fmt(monday)} – ${fmt(sunday)}/${sunday.getFullYear()}`,
  }
}

const REPORT_PROMPT = (start: string, end: string, label: string) =>
  `Tạo báo cáo tuần ${label} cho GoHub (dữ liệu ${start} đến ${end}):

1. **Revenue & GP**: tổng doanh thu + GP, so sánh tuần trước (%)
2. **CM1**: tổng CM1 + CM1%, so với tuần trước
3. **3HK%**: tỷ lệ doanh thu 3HKDATAPOOL / tổng
4. **Top 5 SKU** theo doanh thu tuần này
5. **B2B vs B2C**: breakdown nhanh doanh thu + đơn

Format: tiếng Việt, markdown ngắn gọn (không cần chart), dùng bảng cho số liệu.
Cuối: 2-3 nhận xét chính + 1 điểm chú ý nếu có bất thường.`

export async function GET(req: NextRequest) {
  if (!isCronReq(req)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const chatId = process.env.LARK_WEEKLY_REPORT_CHAT_ID
  if (!chatId) {
    console.warn("[weekly-report] LARK_WEEKLY_REPORT_CHAT_ID chưa set — bỏ qua")
    return NextResponse.json({ ok: false, reason: "LARK_WEEKLY_REPORT_CHAT_ID not set" })
  }

  const { start, end, label } = getWeekRange()

  try {
    const { text } = await runCreatorAI([], REPORT_PROMPT(start, end, label))

    const header  = `📊 *Báo Cáo Tuần ${label}*\n${"─".repeat(30)}\n\n`
    const footer  = `\n\n_Generated by Gấu Pro · ${new Date().toLocaleString("vi-VN", { timeZone: "Asia/Ho_Chi_Minh" })}_`
    const message = header + text + footer

    await sendLarkMessage(chatId, "chat_id", message)
    console.log(`[weekly-report] Đã gửi báo cáo tuần ${label} vào chat ${chatId}`)

    return NextResponse.json({ ok: true, week: label, chars: message.length })
  } catch (err: any) {
    console.error("[weekly-report]", err.message)
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}
