// Bổ sung nước cho VN_TO_EN — SINH TỪ ref_countries (DB) để phủ hết tên nước.
// Trước đây map hardcode thiếu ~161 nước (nhất là TÊN TIẾNG ANH), khiến extractParams không
// trích được nước → chatbot không tìm gói. Merge vào VN_TO_EN lúc build lookup (router.ts).
// Value = đúng tên trong ref_countries.name (để getCountryCodes khớp). Cập nhật bằng harness coverage.

export const COUNTRIES_EXTRA: Record<string, string> = {
  // ── Alias VN / dạng ngắn hay gặp ──
  "mông cổ": "Mongolia",
  "saudi": "Saudi Arabia",
  "ả rập xê út": "Saudi Arabia",
  "nam phi": "South Africa",
  "do thái": "Israel",
  "ma rốc": "Morocco",
  "băng đảo": "Iceland",
  "u crai na": "Ukraine",
  "ai len": "Ireland",
  "bosnia": "Bosnia and Herzegovina",
  "emirates": "United Arab Emirates",
  "czech": "Czech Republic",
  "macedonia": "North Macedonia",
  "congo": "Democratic Republic of the Congo",
  // ── Tên tiếng Anh đầy đủ (sinh từ ref_countries) ──
  "afghanistan": "Afghanistan",
  "aland islands": "Aland Islands",
  "albania": "Albania",
  "algeria": "Algeria",
  "andorra": "Andorra",
  "anguilla": "Anguilla",
  "antigua and barbuda": "Antigua and Barbuda",
  "armenia": "Armenia",
  "aruba": "Aruba",
  "austria": "Austria",
  "azerbaijan": "Azerbaijan",
  "azores": "Azores",
  "bahamas": "Bahamas",
  "bahrain": "Bahrain",
  "balearic islands": "Balearic Islands",
  "bangladesh": "Bangladesh",
  "barbados": "Barbados",
  "belarus": "Belarus",
  "belgium": "Belgium",
  "benin": "Benin",
  "bhutan": "Bhutan",
  "bolivia": "Bolivia",
  "bosnia and herzegovina": "Bosnia and Herzegovina",
  "botswana": "Botswana",
  "brunei": "Brunei",
  "bulgaria": "Bulgaria",
  "burkina faso": "Burkina Faso",
  "cambodia": "Cambodia",
  "cameroon": "Cameroon",
  "canary islands": "Canary Islands",
  "cape verde": "Cape Verde",
  "central african republic": "Central African Republic",
  "chad": "Chad",
  "chatham islands": "Chatham Islands",
  "comoros": "Comoros",
  "corfu": "Corfu",
  "costa rica": "Costa Rica",
  "cote d'ivoire": "Cote d'Ivoire",
  "crete": "Crete",
  "cuba": "Cuba",
  "curacao": "Curacao",
  "cyclades islands": "Cyclades Islands",
  "cyprus": "Cyprus",
  "democratic republic of the congo": "Democratic Republic of the Congo",
  "dominican republic": "Dominican Republic",
  "ecuador": "Ecuador",
  "el salvador": "El Salvador",
  "equatorial guinea": "Equatorial Guinea",
  "estonia": "Estonia",
  "faroe islands": "Faroe Islands",
  "fiji": "Fiji",
  "french guyana": "French Guyana",
  "french polynesia": "French Polynesia",
  "gabon": "Gabon",
  "georgia": "Georgia",
  "gibraltar": "Gibraltar",
  "greenland": "Greenland",
  "grenada": "Grenada",
  "guadeloup": "Guadeloup",
  "guatemala": "Guatemala",
  "guernsey": "Guernsey",
  "guinea-bissau": "Guinea-Bissau",
  "guyana": "Guyana",
  "honduras": "Honduras",
  "iceland": "Iceland",
  "iran": "Iran",
  "iraq": "Iraq",
  "ireland": "Ireland",
  "isle of man": "Isle of Man",
  "israel": "Israel",
  "ivory coast": "Ivory Coast",
  "jamaica": "Jamaica",
  "jersey": "Jersey",
  "jordan": "Jordan",
  "kazakhstan": "Kazakhstan",
  "kosovo": "Kosovo",
  "kuwait": "Kuwait",
  "kyrgyzstan": "Kyrgyzstan",
  "laos": "Laos",
  "latvia": "Latvia",
  "lebanon": "Lebanon",
  "lesotho": "Lesotho",
  "liberia": "Liberia",
  "liechtenstein": "Liechtenstein",
  "lithuania": "Lithuania",
  "luxembourg": "Luxembourg",
  "macau": "Macau",
  "madagascar": "Madagascar",
  "madeira": "Madeira",
  "maldives": "Maldives",
  "mali": "Mali",
  "malta": "Malta",
  "marie-galante island": "Marie-Galante Island",
  "martinica": "Martinica",
  "martinique": "Martinique",
  "mauritania": "Mauritania",
  "mauritius": "Mauritius",
  "mayotte": "Mayotte",
  "moldova": "Moldova",
  "mongolia": "Mongolia",
  "montenegro": "Montenegro",
  "montserrat": "Montserrat",
  "morocco": "Morocco",
  "mozambique": "Mozambique",
  "nepal": "Nepal",
  "new caledonia": "New Caledonia",
  "nicaragua": "Nicaragua",
  "niger": "Niger",
  "north macedonia": "North Macedonia",
  "northern cyprus": "Northern Cyprus",
  "oman": "Oman",
  "pakistan": "Pakistan",
  "palestinian territory occupied": "Palestinian Territory, Occupied",
  "panama": "Panama",
  "papua new guinea": "Papua New Guinea",
  "paraguay": "Paraguay",
  "pensida island": "Pensida Island",
  "peru": "Peru",
  "puerto rico": "Puerto Rico",
  "qatar": "Qatar",
  "reunion island": "Reunion Island",
  "rhodes": "Rhodes",
  "rwanda": "Rwanda",
  "saint barthelemy": "Saint Barthelemy",
  "saint islands": "Saint Islands",
  "saint kitts and nevis": "Saint Kitts and Nevis",
  "saint lucia": "Saint Lucia",
  "saint martin": "Saint Martin",
  "saint vincent and the grenadines": "Saint Vincent and the Grenadines",
  "san marino": "San Marino",
  "sardinia": "Sardinia",
  "senegal": "Senegal",
  "seychelles": "Seychelles",
  "sicily": "Sicily",
  "sierra leone": "Sierra Leone",
  "slovakia": "Slovakia",
  "slovenia": "Slovenia",
  "south africa": "South Africa",
  "sri lanka": "Sri Lanka",
  "st pierre and miquelon island": "St Pierre and Miquelon Island",
  "suriname": "Suriname",
  "syria": "Syria",
  "tajikistan": "Tajikistan",
  "tanzania": "Tanzania",
  "tasmania": "Tasmania",
  "togo": "Togo",
  "tonga": "Tonga",
  "trinidad and tobago": "Trinidad and Tobago",
  "tunisia": "Tunisia",
  "turks and caicos islands": "Turks and Caicos Islands",
  "uganda": "Uganda",
  "ukraine": "Ukraine",
  "united arab emirates": "United Arab Emirates",
  "uruguay": "Uruguay",
  "uzbekistan": "Uzbekistan",
  "vanuatu": "Vanuatu",
  "vatican": "Vatican",
  "venezuela": "Venezuela",
  "virgin islands": "Virgin Islands (British)",
  "yemen": "Yemen",
  "zambia": "Zambia",
}
